src/app/FacesWebApp/Models/ErrorViewModel.cs
using System;

namespace FacesWebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/app/FacesWebApp/ViewModels/OrderDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FacesWebApp.ViewModels
{
    public class OrderDetailViewModel
    {
        public int OrderDetailId { get; set; }
        public byte[] FaceData { get; set; }
        public string ImageString { get; set; }
    }
}

src/app/FacesWebApp/ViewModels/OrderViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FacesWebApp.ViewModels
{
    public class OrderViewModel
    {
        [Display(Name = "Order Id")]
        public Guid OrderId { get; set; }

        [Display(Name = "Email")]
        public string UserEmail { get; set; }

        [Display(Name = "Image File")]
        public IFormFile ImageFile { get; set; }

        [Display(Name = "Image URL")]
        public string PictureUrl { get; set; }

        [Display(Name = "Order Status")]
        public string OrderStatus { get; set; }
        
        public byte[] ImageData { get; set; }
        public string ImageString { get; set; }
        public List<OrderDetailViewModel> OrderDetails { get; set; }
    }
}

src/app/FacesWebApp/Controllers/HomeController.cs
using Events;
using FacesWebApp.Models;
using FacesWebApp.RestClients;
using FacesWebApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Diagnostics;
using System.IO;
using System.Threading.Tasks;

namespace FacesWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        // private readonly IEventBus _eventBus;
        private readonly IOrderManagementAPI _orderManagementAPI;
        public HomeController(ILogger<HomeController> logger, IOrderManagementAPI orderManagementAPI)
        {
            _logger = logger;
            _orderManagementAPI = orderManagementAPI;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [HttpGet]
        public IActionResult RegisterOrder()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> RegisterOrder(OrderViewModel model)
        {
            MemoryStream ms = new();
            using var uploadedFile = model.ImageFile.OpenReadStream();
            await uploadedFile.CopyToAsync(ms);
            model.ImageData = ms.ToArray();
            model.PictureUrl = model.ImageFile.FileName;
            model.OrderId = Guid.NewGuid();
            var message = new RegisterOrderIntegrationEvent
            {
                OrderId = model.OrderId,
                UserEmail = model.UserEmail,
                ImageData = model.ImageData,
                PictureUrl = model.PictureUrl
            };
            //var sendToUri = new Uri($"{RabbitMqMassTransitConstants.RabbitMqUri}"
            //    + $"{RabbitMqMassTransitConstants.RegisterOrderCommandQueue }");
            //var endpoint = await _busControl.GetSendEndpoint(sendToUri);
            //await endpoint.Send<IRegisterOrderCommand>(new
            //{
            //    model.OrderId,
            //    model.UserEmail,
            //    model.ImageData,
            //    model.PictureUrl
            //});
            // await _eventBus.PublishAsync<RegisterOrderIntegrationEvent>(message);
            await _orderManagementAPI.CreateOrderAsync(message);
            ViewData["OrderId"] = model.OrderId;
            return View("Thanks");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/app/FacesWebApp/Controllers/OrderManagementController.cs
using FacesWebApp.RestClients;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FacesWebApp.Controllers
{
    public class OrderManagementController : Controller
    {
        private readonly IOrderManagementAPI _orderManagementAPI;
        public OrderManagementController(IOrderManagementAPI orderManagementAPI)
        {
            _orderManagementAPI = orderManagementAPI;
        }
        public async Task<IActionResult> Index()
        {
            var orders = await _orderManagementAPI.GetOrders();
            foreach (var order in orders)
            {
                order.ImageString = ConvertAndFormatToString(order.ImageData);
            }
            return View(orders);
        }

        [Route("/Details/{orderId}")]
        public async Task<IActionResult> Details(string orderId)
        {
            var order = await _orderManagementAPI.GetOrderById(Guid.Parse(orderId));
            order.ImageString = ConvertAndFormatToString(order.ImageData);
            foreach(var detail in order.OrderDetails)
            {
                detail.ImageString = ConvertAndFormatToString(detail.FaceData);
            }
            return View(order);
        }

        private string ConvertAndFormatToString(byte[] imageData)
        {
            string imageBase64Data = Convert.ToBase64String(imageData);
            return string.Format("data:image/png;base64, {0}", imageBase64Data);
        }
    }
}

src/app/FacesWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/app/FacesWebApp/Views/Home/RegisterOrder.cshtml
@model OrderViewModel
@{
    ViewData["Title"] = "Register Order Page";
}

<div>
    <img src="~/images/faceslogo.png" />
    <h2>Order Registeration</h2>
</div>

<form asp-controller="Home" asp-action="RegisterOrder" enctype="multipart/form-data">
    <div class="row">
        <div class="col-md-10">
            <h3> Enter your email address and upload your picture</h3>
            <div class="form-group">
                <label asp-for="UserEmail"></label>
                <input asp-for="UserEmail" class="form-control" />
            </div>
        </div>
        <div class="col-md-10">
            <p>Upload Image File</p>
            <input type="file" name="ImageFile" />
        </div>
    </div>
    <input type="submit" class="btn btn-info" value="Submit" />
</form>

src/app/FacesWebApp/Views/Home/Thanks.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h2>Thanks for your Order: @ViewData["OrderId"]</h2>

src/app/FacesWebApp/Views/OrderManagement/Details.cshtml
@model OrderViewModel
@{ 
    ViewData["Title"] = "Order Details";
}

<h3>Order Details: </h3>
Order Id: @Model.OrderId
User Email: @Model.UserEmail
Picture: <img src="@Model.ImageString" width="100px" height="100px" />
Status: @Model.OrderStatus
<table class="table">
    <thead>
        <tr>
            <th>Order Detail Id</th>
            <th>Image</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var detail in Model.OrderDetails)
        {
            <tr>
                <td>@detail.OrderDetailId</td>
                <td><img src="@detail.ImageString" width="50px" height="50px" /></td>
            </tr>
        }
    </tbody>
</table>

src/app/FacesWebApp/Views/OrderManagement/Index.cshtml
@model List<OrderViewModel>
@{ 
    ViewData["Title"] = "Orders List";
}

<h3>Orders Management - Overview</h3>
<table class="table">
    <thead>
        <tr>
            <th>Order Id</th>
            <th>User Email</th>
            <th>Image</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var order in Model)
        {
        <tr class="clickable" onclick="location.href = '@Url.Action("Details", "OrderManagement", new { orderId = order.OrderId})'">
            <td>@order.OrderId</td>
            <td>@order.UserEmail</td>
            <td><img src="@order.ImageString" width="50px" height="50px" /></td>
            <td>@order.OrderStatus</td>
        </tr>
        }
    </tbody>
</table>

src/app/FacesWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Faces Web App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Faces.WebMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="RegisterOrder">Register Order</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OrderManagement" asp-action="Index">Order Management</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Faces Web App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>